USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE DATABASE IF NOT EXISTS YC_DB;
CREATE SCHEMA IF NOT EXISTS YC_SCHEMA;

CREATE STAGE IF NOT EXISTS MY_STAGE;

CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
RECORD_DELIMITER = '\n'
FIELD_DELIMITER = ','
NULL_IF = ('NULL', 'null', '')
EMPTY_FIELD_AS_NULL = TRUE;

PUT file:///workspaces/Project-YC/companies.csv @MY_STAGE;

CREATE OR REPLACE TABLE COMPANIES (
    NAME VARCHAR,
    DESCRIPTION VARCHAR,
    LOCATION VARCHAR,
    TAGS VARCHAR
);

COPY INTO COMPANIES
FROM @MY_STAGE
FILE_FORMAT = MY_CSV_FORMAT;